### PR TITLE
fix: keep sqlite memory db alive

### LINKED ISSUE #354: sqlite in-memory database disappears and ledger crashes
### Description
When starting the ledger with an in-memory sqlite database, the database disappears after a few minutes. When the ledger tries to query a (non-existing) table, it crashes.

### Steps to reproduce
Open terminal, switch into the root folder of the ledger repo and run

```
LEDGER_PORT=3001 \
LEDGER_PUBLIC_URI=http://192.168.56.1:3001 \
LEDGER_ILP_PREFIX=demo.ledger2. \
LEDGER_DB_URI=sqlite://:memory: \
LEDGER_ADMIN_PASS="mypassword" \
DEBUG=* \
npm start
```

Wait a few minutes. Then, execute `curl http://localhost:3001` and the ledger will fill with:
```
2016-11-09T11:45:06.321Z error-handler error { Error: SQLITE_ERROR: no such table: L_ACCOUNTS errno: 1, code: 'SQLITE_ERROR' }
2016-11-09T11:45:06.321Z error-handler error Error: SQLITE_ERROR: no such table: L_ACCOUNTS
```

The problem might be that the connection to the in-memory database is released and, thus, sqlite removes the database. See [here](http://stackoverflow.com/questions/3698130/sqlite-table-not-saving).

### PR DESCRIPTION
**Pull request by justmoon**
Change the pool settings for Knex to prevent the database connection
from being cleaned up.

Fixes #354.

### CODE REVIEW

**Comment by dappelt** [comment]
Doesn't fix it for me. The sqlite db still disappears.

I also tried some of the other config values mentioned [here](https://github.com/tgriesser/knex/issues/1701), but it did not help neither.

**Comment by justmoon** [comment]
Weird, I tested with this patch and without and I was able to reproduce the issue without this patch, but it disappeared once I applied this patch. Hmm.

Can you post your Node version, Knex version and OS?

**Comment by dappelt** [comment]
Did you wait a few minutes before testing if the DB is still there? It takes a couple of minutes for the DB to disappear.

Here is the version info you asked for:
```sh
➜  five-bells-ledger git:(fix/st-keep-memory-db-alive) ✗ node -v
v7.1.0
➜  five-bells-ledger git:(fix/st-keep-memory-db-alive) ✗ npm ls knex
five-bells-ledger@19.1.0 .../interledgerjs/five-bells-ledger
├── ....
├── knex@0.12.6
....
➜  five-bells-ledger git:(fix/st-keep-memory-db-alive) ✗ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G31
```

I am starting the ledger with the same parameters as reported in the issue, i.e.:
```sh
five-bells-ledger git:(fix/st-keep-memory-db-alive) LEDGER_PORT=3001 \
LEDGER_PUBLIC_URI=http://localhost:3001 \
LEDGER_ILP_PREFIX=demo.ledger2. \
LEDGER_DB_URI=sqlite://:memory: \
LEDGER_ADMIN_PASS="mypassword" \
DEBUG=* \
npm start
```

After waiting two minutes, I request http://localhost:3001/accounts/admin and I get the same error message as reported in the issue:
```sh
Unhandled rejection Error: SQLITE_ERROR: no such table: L_ACCOUNTS
```

**Comment by justmoon** [comment]
Closing since we are deprioritizing SQLite.

**Pull request closed without merging**
